import type { AppData } from "./types";

export const demoData: AppData = {
  users: [
    {
      id: "user-ana",
      firstName: "Ana",
      lastName: "Martinez",
      email: "ana.martinez@empresa.com",
      area: "Marketing",
      createdAt: "2026-04-01T12:00:00.000Z",
    },
    {
      id: "user-lucas",
      firstName: "Lucas",
      lastName: "Pereyra",
      email: "lucas.pereyra@empresa.com",
      area: "Producto",
      createdAt: "2026-04-01T12:10:00.000Z",
    },
    {
      id: "user-sofia",
      firstName: "Sofia",
      lastName: "Gomez",
      email: "sofia.gomez@empresa.com",
      area: "Finanzas",
      createdAt: "2026-04-01T12:20:00.000Z",
    },
  ],
  matches: [
    {
      id: "match-1",
      dateLabel: "Fecha 1",
      dateVisible: true,
      startsAt: "2026-04-10T19:00:00.000Z",
      homeTeam: "Mexico",
      awayTeam: "Sudafrica",
      result: { outcome: "home", homeScore: 2, awayScore: 1 },
    },
    {
      id: "match-2",
      dateLabel: "Fecha 1",
      dateVisible: true,
      startsAt: "2026-06-12T22:00:00.000Z",
      homeTeam: "Canada",
      awayTeam: "Japon",
    },
    {
      id: "match-3",
      dateLabel: "Fecha 2",
      dateVisible: true,
      startsAt: "2026-06-15T16:00:00.000Z",
      homeTeam: "Argentina",
      awayTeam: "Italia",
    },
    {
      id: "match-4",
      dateLabel: "Fecha 2",
      dateVisible: true,
      startsAt: "2026-06-15T19:00:00.000Z",
      homeTeam: "Brasil",
      awayTeam: "Espana",
    },
    {
      id: "match-5",
      dateLabel: "Fecha 3",
      dateVisible: true,
      startsAt: "2026-06-19T21:00:00.000Z",
      homeTeam: "Francia",
      awayTeam: "Alemania",
    },
    {
      id: "match-6",
      dateLabel: "Fecha 3",
      dateVisible: false,
      startsAt: "2026-06-20T18:00:00.000Z",
      homeTeam: "Uruguay",
      awayTeam: "Portugal",
    },
  ],
  predictions: [
    {
      id: "prediction-1",
      userId: "user-ana",
      matchId: "match-1",
      outcome: "home",
      updatedAt: "2026-04-01T13:00:00.000Z",
    },
    {
      id: "prediction-2",
      userId: "user-lucas",
      matchId: "match-1",
      outcome: "draw",
      updatedAt: "2026-04-01T13:05:00.000Z",
    },
    {
      id: "prediction-3",
      userId: "user-sofia",
      matchId: "match-1",
      outcome: "home",
      updatedAt: "2026-04-01T13:10:00.000Z",
    },
    {
      id: "prediction-4",
      userId: "user-ana",
      matchId: "match-2",
      outcome: "away",
      updatedAt: "2026-04-01T13:15:00.000Z",
    },
    {
      id: "prediction-5",
      userId: "user-lucas",
      matchId: "match-2",
      outcome: "draw",
      updatedAt: "2026-04-01T13:20:00.000Z",
    },
  ],
};
